language: rust
cache:
  cargo: true
  directories:
    - debug-plugin/target
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - env

script:
  - cargo build
  - cargo test
  - cargo build --features "serde log"
  - cargo test --features "serde log"
  - cd debug-plugin; cargo build

notifications:
  email:
    on_success: never
    on_failure: never
